name: Deploy na AWS via OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCOUNT_ID: 202853071953
  AWS_REGION: us-east-1
  ECR_REPOSITORY: cloudsecureapp
  ECS_CLUSTER_NAME: cloudsecureapp
  ECS_SERVICE_NAME: cloudsecureapp
  ECS_TASK_DEFINITION: cloudsecureapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS com OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::202853071953:role/GITHUB_DEPLOY_ROLE
          aws-region: ${{ env.AWS_REGION }}

      - name: Verificar identidade atual da AWS
        run: aws sts get-caller-identity

      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build da imagem Docker
        run: docker build -t $ECR_REPOSITORY .

      - name: Tag da imagem para o ECR
        run: docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push da imagem para o ECR
        run: docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Atualizar serviço ECS para usar a nova imagem
        run: |
          TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION)

          NEW_TASK_DEF_JSON=$(echo $TASK_DEF_JSON | jq --arg IMAGE "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest" \
            '.taskDefinition | 
            .containerDefinitions[0].image = $IMAGE |
            {family: .family, containerDefinitions: .containerDefinitions, cpu: .cpu, memory: .memory, networkMode: .networkMode, requiresCompatibilities: .requiresCompatibilities, executionRoleArn: .executionRoleArn}' )

          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json "$NEW_TASK_DEF_JSON" \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "Nova task definition registrada: $NEW_TASK_DEF_ARN"

          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $NEW_TASK_DEF_ARN

          echo "Serviço ECS atualizado com nova task definition"
